# Generated by Django 4.1.3 on 2024-02-17 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("courses", models.TextField(blank=True, null=True)),
                ("institution", models.TextField(blank=True, null=True)),
                ("startdate", models.TextField(blank=True, null=True)),
                ("enddate", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="demooutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("demooutputs", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Demoquestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questions", models.TextField()),
            ],
            options={
                "db_table": "Demoquestions",
            },
        ),
        migrations.CreateModel(
            name="Educations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school", models.TextField(blank=True, null=True)),
                ("degree", models.TextField(blank=True, null=True)),
                ("startdate", models.TextField(blank=True, null=True)),
                ("enddate", models.TextField(blank=True, null=True)),
                ("city", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Educationsresume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ugname", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "uglocations",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("ugstartdate", models.DateField(blank=True, null=True)),
                ("ugenddate", models.DateField(blank=True, null=True)),
                (
                    "ugfieldstudy",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("ugdegree", models.CharField(blank=True, max_length=300, null=True)),
                ("ugdescriptions", models.TextField(blank=True, null=True)),
                ("xiiname", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "xiilocations",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("xiistartdate", models.DateField(blank=True, null=True)),
                ("xiienddate", models.DateField(blank=True, null=True)),
                (
                    "xiifieldstudy",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("xiidegree", models.CharField(blank=True, max_length=300, null=True)),
                ("xiidescriptions", models.TextField(blank=True, null=True)),
                ("xname", models.CharField(blank=True, max_length=200, null=True)),
                ("xlocations", models.CharField(blank=True, max_length=200, null=True)),
                ("xstartdate", models.DateField(blank=True, null=True)),
                ("xenddate", models.DateField(blank=True, null=True)),
                (
                    "xfieldstudy",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("xdegree", models.CharField(blank=True, max_length=300, null=True)),
                ("xdescriptions", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jobtitle", models.TextField(blank=True, null=True)),
                ("employer", models.TextField(blank=True, null=True)),
                ("startdate", models.TextField(blank=True, null=True)),
                ("enddate", models.TextField(blank=True, null=True)),
                ("city", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ExtraCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("functiontype", models.TextField(blank=True, null=True)),
                ("employer", models.TextField(blank=True, null=True)),
                ("startdate", models.TextField(blank=True, null=True)),
                ("enddate", models.TextField(blank=True, null=True)),
                ("city", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Hobbies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hobbielist", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Interships",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jobtitle", models.TextField(blank=True, null=True)),
                ("employer", models.TextField(blank=True, null=True)),
                ("startdate", models.TextField(blank=True, null=True)),
                ("enddate", models.TextField(blank=True, null=True)),
                ("city", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Personaldetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jobtitle", models.TextField(blank=True, null=True)),
                ("photo", models.TextField(blank=True, null=True)),
                ("name", models.TextField(blank=True, null=True)),
                ("lastname", models.TextField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
                ("phone", models.TextField(blank=True, null=True)),
                ("country", models.TextField(blank=True, null=True)),
                ("city", models.TextField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("postcode", models.TextField(blank=True, null=True)),
                ("nationality", models.TextField(blank=True, null=True)),
                ("placeofbirth", models.TextField(blank=True, null=True)),
                ("dateofbirth", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Practicelevels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "TrialProcut",
            },
        ),
        migrations.CreateModel(
            name="Profilesummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Programminglan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "Programming_languages",
            },
        ),
        migrations.CreateModel(
            name="Projectresume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500, null=True)),
                ("descriptions", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Questionpractices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(blank=True, max_length=100, null=True)),
                ("content", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Reference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(blank=True, null=True)),
                ("company", models.TextField(blank=True, null=True)),
                ("phone", models.TextField(blank=True, null=True)),
                ("email", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill", models.TextField(blank=True, null=True)),
                ("level", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lable", models.TextField(blank=True, null=True)),
                ("link", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TechnicalQuestionsTestcase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questions", models.TextField()),
                ("sinput", models.TextField()),
                ("soutput", models.TextField()),
                ("tinput", models.TextField()),
                ("toutput", models.TextField()),
                ("samplecode", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TemplatedesignImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                ("link", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Toutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("toutputs", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Userclick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userclickid", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Templatedesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.templatedesignimage",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(auto_now_add=True)),
                ("end_date", models.DateField()),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "TrialSubcription",
            },
        ),
    ]
