# Generated by Django 4.1.3 on 2024-02-17 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionpractices",
            name="title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="coreapp.practicelevels",
            ),
        ),
    ]
