# Generated by Django 4.1.3 on 2024-02-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0006_titletestcase_technicalquestionstestcase_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Javatraingtitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
