# Generated by Django 4.1.3 on 2024-02-21 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0008_javatraingtitle_selecttype"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mcqjavatraning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Questions", models.TextField(blank=True, null=True)),
                ("optiona", models.CharField(blank=True, max_length=100, null=True)),
                ("optionb", models.CharField(blank=True, max_length=100, null=True)),
                ("optionc", models.CharField(blank=True, max_length=100, null=True)),
                ("optiond", models.CharField(blank=True, max_length=100, null=True)),
                ("correctans", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.javatraingtitle",
                    ),
                ),
            ],
        ),
    ]
