# Generated by Django 4.1.3 on 2024-02-21 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0011_remove_mcqjavatraning_questions_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Javatraingmcq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questions", models.TextField(blank=True, null=True)),
                ("optiona", models.TextField(blank=True, null=True)),
                ("optionb", models.TextField(blank=True, null=True)),
                ("optionc", models.TextField(blank=True, null=True)),
                ("optiond", models.TextField(blank=True, null=True)),
                ("correctans", models.TextField(blank=True, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.javatraingtitle",
                    ),
                ),
            ],
        ),
    ]
