# Generated by Django 4.1.3 on 2024-02-25 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0013_alter_mcqjavatraning_title_videosection"),
    ]

    operations = [
        migrations.CreateModel(
            name="Traningcodeingquestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questions", models.TextField()),
                ("sinput", models.TextField()),
                ("soutput", models.TextField()),
                ("tinput", models.TextField()),
                ("toutput", models.TextField()),
                ("samplecode", models.TextField(blank=True, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.javatraingtitle",
                    ),
                ),
            ],
        ),
    ]
