# Generated by Django 4.1.3 on 2024-02-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0014_traningcodeingquestions"),
    ]

    operations = [
        migrations.CreateModel(
            name="Traningupdateid",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updateid", models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
