# Generated by Django 4.1.3 on 2024-02-26 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0015_traningupdateid"),
    ]

    operations = [
        migrations.CreateModel(
            name="Demovideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("video_file", models.FileField(upload_to="videos/")),
                ("content", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
