# Generated by Django 4.1.3 on 2024-02-26 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0016_demovideo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="demovideo",
            old_name="title",
            new_name="titl",
        ),
        migrations.CreateModel(
            name="Uploadvideosections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titleone", models.CharField(max_length=100)),
                ("video_file", models.FileField(upload_to="videos/")),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.javatraingtitle",
                    ),
                ),
            ],
        ),
    ]
