# Generated by Django 4.1.3 on 2024-02-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0017_rename_title_demovideo_titl_uploadvideosections"),
    ]

    operations = [
        migrations.CreateModel(
            name="Titleclick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cliknum", models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
