# Generated by Django 4.1.3 on 2024-02-27 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0018_titleclick"),
    ]

    operations = [
        migrations.AddField(
            model_name="titleclick",
            name="title",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
