# Generated by Django 4.1.3 on 2024-03-02 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0020_quiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="answer1",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="answer2",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="answer3",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="answer4",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="quiz",
            name="title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="coreapp.javatraingtitle",
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="answer",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="option1",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="option2",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="option3",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="option4",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="question",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
