# Generated by Django 4.1.3 on 2024-03-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "coreapp",
            "0021_quiz_answer1_quiz_answer2_quiz_answer3_quiz_answer4_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckboxState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option1", models.BooleanField(default=False)),
                ("option2", models.BooleanField(default=False)),
                ("option3", models.BooleanField(default=False)),
                ("option4", models.BooleanField(default=False)),
            ],
        ),
    ]
