# Generated by Django 4.1.3 on 2024-03-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0022_checkboxstate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="answer1",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="answer2",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="answer3",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="answer4",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
