# Generated by Django 4.1.3 on 2024-03-02 05:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0023_alter_quiz_answer1_alter_quiz_answer2_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CheckboxState",
        ),
    ]
