# Generated by Django 4.1.3 on 2024-03-04 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0025_aptitudetitle_aptitudevideosections_aptitudequiz"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pdtitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pdvideosections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titleone", models.CharField(max_length=100)),
                ("video_file", models.FileField(upload_to="pd/")),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.aptitudetitle",
                    ),
                ),
            ],
        ),
    ]
