# Generated by Django 4.1.3 on 2024-03-04 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0026_pdtitle_pdvideosections"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdvideosections",
            name="title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="coreapp.pdtitle",
            ),
        ),
    ]
