# Generated by Django 4.1.3 on 2024-03-06 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0028_apptitle_appquiz"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appquiz",
            name="title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="coreapp.apptitle",
            ),
        ),
    ]
