# Generated by Django 4.1.3 on 2024-03-08 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0030_workshoptitle_workshopvideosections_workshopquiz"),
    ]

    operations = [
        migrations.CreateModel(
            name="Intershiptitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
                ("timer", models.CharField(blank=True, max_length=1000, null=True)),
                ("part", models.CharField(blank=True, max_length=1000, null=True)),
                ("code", models.CharField(blank=True, max_length=1000, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("image", models.ImageField(null=True, upload_to="Interships/")),
            ],
        ),
        migrations.AlterField(
            model_name="workshoptitle",
            name="image",
            field=models.ImageField(null=True, upload_to="imageworkshop/"),
        ),
        migrations.CreateModel(
            name="Intershipvideosections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titleone", models.CharField(max_length=100)),
                ("video_file", models.FileField(upload_to="Interships/")),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.intershiptitle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Intershipquiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(blank=True, max_length=1000, null=True)),
                ("option1", models.CharField(blank=True, max_length=1000, null=True)),
                ("option2", models.CharField(blank=True, max_length=1000, null=True)),
                ("option3", models.CharField(blank=True, max_length=1000, null=True)),
                ("option4", models.CharField(blank=True, max_length=1000, null=True)),
                ("answer", models.CharField(blank=True, max_length=1000, null=True)),
                ("answer1", models.CharField(blank=True, max_length=100, null=True)),
                ("answer2", models.CharField(blank=True, max_length=100, null=True)),
                ("answer3", models.CharField(blank=True, max_length=100, null=True)),
                ("answer4", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.intershiptitle",
                    ),
                ),
            ],
        ),
    ]
