# Generated by Django 4.1.3 on 2024-03-11 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0032_etechnicaltitle_etechnicalvideosections_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ebusinesstitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
                ("subtitle", models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Espokentitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
                ("subtitle", models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Espokenvideosections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titleone", models.CharField(max_length=100)),
                ("video_file", models.FileField(upload_to="Espokens/")),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.espokentitle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Espokenquiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(blank=True, max_length=1000, null=True)),
                ("option1", models.CharField(blank=True, max_length=1000, null=True)),
                ("option2", models.CharField(blank=True, max_length=1000, null=True)),
                ("option3", models.CharField(blank=True, max_length=1000, null=True)),
                ("option4", models.CharField(blank=True, max_length=1000, null=True)),
                ("answer", models.CharField(blank=True, max_length=1000, null=True)),
                ("answer1", models.CharField(blank=True, max_length=100, null=True)),
                ("answer2", models.CharField(blank=True, max_length=100, null=True)),
                ("answer3", models.CharField(blank=True, max_length=100, null=True)),
                ("answer4", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.espokentitle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ebusinessvideosections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titleone", models.CharField(max_length=100)),
                ("video_file", models.FileField(upload_to="Ebusinesss/")),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.ebusinesstitle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ebusinessquiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(blank=True, max_length=1000, null=True)),
                ("option1", models.CharField(blank=True, max_length=1000, null=True)),
                ("option2", models.CharField(blank=True, max_length=1000, null=True)),
                ("option3", models.CharField(blank=True, max_length=1000, null=True)),
                ("option4", models.CharField(blank=True, max_length=1000, null=True)),
                ("answer", models.CharField(blank=True, max_length=1000, null=True)),
                ("answer1", models.CharField(blank=True, max_length=100, null=True)),
                ("answer2", models.CharField(blank=True, max_length=100, null=True)),
                ("answer3", models.CharField(blank=True, max_length=100, null=True)),
                ("answer4", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.ebusinesstitle",
                    ),
                ),
            ],
        ),
    ]
