# Generated by Django 4.1.3 on 2024-03-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0034_elisteningtitle_elisteningreader_elisteningquiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="elisteningtitle",
            name="titleone",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
