# Generated by Django 4.1.3 on 2024-03-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0036_ctitlepractices_cquestionpractices"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ctitletestcase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
                ("level", models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
