# Generated by Django 4.1.3 on 2024-03-17 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0038_ctechnicalquestionstestcase"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ctechnicalquestionstestcase",
            name="title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="coreapp.ctitletestcase",
            ),
        ),
    ]
