# Generated by Django 4.1.3 on 2024-03-21 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0040_ptitlepractices_ptitletestcase_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cpponetitlepractices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
                ("level", models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cpponetitletestcase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
                ("level", models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Cpptraingtitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
                ("selecttype", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ctraingtitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
                ("selecttype", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pythontraingtitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
                ("selecttype", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pythonuploadvideosections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titleone", models.CharField(max_length=100)),
                ("video_file", models.FileField(upload_to="videos/")),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.pythontraingtitle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pythontraningcodeingquestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questions", models.TextField()),
                ("sinput", models.TextField()),
                ("soutput", models.TextField()),
                ("tinput", models.TextField()),
                ("toutput", models.TextField()),
                ("samplecode", models.TextField(blank=True, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.pythontraingtitle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pythonquiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(blank=True, max_length=1000, null=True)),
                ("option1", models.CharField(blank=True, max_length=1000, null=True)),
                ("option2", models.CharField(blank=True, max_length=1000, null=True)),
                ("option3", models.CharField(blank=True, max_length=1000, null=True)),
                ("option4", models.CharField(blank=True, max_length=1000, null=True)),
                ("answer", models.CharField(blank=True, max_length=1000, null=True)),
                ("answer1", models.CharField(blank=True, max_length=100, null=True)),
                ("answer2", models.CharField(blank=True, max_length=100, null=True)),
                ("answer3", models.CharField(blank=True, max_length=100, null=True)),
                ("answer4", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.pythontraingtitle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cuploadvideosections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titleone", models.CharField(max_length=100)),
                ("video_file", models.FileField(upload_to="videos/")),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.ctraingtitle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ctraningcodeingquestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questions", models.TextField()),
                ("sinput", models.TextField()),
                ("soutput", models.TextField()),
                ("tinput", models.TextField()),
                ("toutput", models.TextField()),
                ("samplecode", models.TextField(blank=True, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.ctraingtitle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cquiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(blank=True, max_length=1000, null=True)),
                ("option1", models.CharField(blank=True, max_length=1000, null=True)),
                ("option2", models.CharField(blank=True, max_length=1000, null=True)),
                ("option3", models.CharField(blank=True, max_length=1000, null=True)),
                ("option4", models.CharField(blank=True, max_length=1000, null=True)),
                ("answer", models.CharField(blank=True, max_length=1000, null=True)),
                ("answer1", models.CharField(blank=True, max_length=100, null=True)),
                ("answer2", models.CharField(blank=True, max_length=100, null=True)),
                ("answer3", models.CharField(blank=True, max_length=100, null=True)),
                ("answer4", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.ctraingtitle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cppuploadvideosections",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titleone", models.CharField(max_length=100)),
                ("video_file", models.FileField(upload_to="videos/")),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.cpptraingtitle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cpptraningcodeingquestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questions", models.TextField()),
                ("sinput", models.TextField()),
                ("soutput", models.TextField()),
                ("tinput", models.TextField()),
                ("toutput", models.TextField()),
                ("samplecode", models.TextField(blank=True, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.cpptraingtitle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cppquiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(blank=True, max_length=1000, null=True)),
                ("option1", models.CharField(blank=True, max_length=1000, null=True)),
                ("option2", models.CharField(blank=True, max_length=1000, null=True)),
                ("option3", models.CharField(blank=True, max_length=1000, null=True)),
                ("option4", models.CharField(blank=True, max_length=1000, null=True)),
                ("answer", models.CharField(blank=True, max_length=1000, null=True)),
                ("answer1", models.CharField(blank=True, max_length=100, null=True)),
                ("answer2", models.CharField(blank=True, max_length=100, null=True)),
                ("answer3", models.CharField(blank=True, max_length=100, null=True)),
                ("answer4", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.cpptraingtitle",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CpponetechnicalQuestionsTestcase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("questions", models.TextField()),
                ("sinput", models.TextField()),
                ("soutput", models.TextField()),
                ("tinput", models.TextField()),
                ("toutput", models.TextField()),
                ("samplecode", models.TextField(blank=True, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.cpponetitletestcase",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cpponepquestionpractices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.ptitlepractices",
                    ),
                ),
            ],
        ),
    ]
