# Generated by Django 4.1.3 on 2024-03-28 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("coreapp", "0044_ctraingtitle_mcqscore_ctraingtitle_mcqtotal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ctraingtitle",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
