# Generated by Django 4.1.3 on 2024-04-01 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0046_ctraningreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ctestcasereport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("success", models.CharField(blank=True, max_length=1000, null=True)),
                ("failed", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "testcase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.ctechnicalquestionstestcase",
                    ),
                ),
                (
                    "title",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.ctitletestcase",
                    ),
                ),
            ],
        ),
    ]
