# Generated by Django 4.1.3 on 2024-04-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0052_alter_javatestcasereport_testcase_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Uploademployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topice", models.TextField()),
                ("upload", models.TextField()),
            ],
            options={
                "db_table": "Uploademployee",
            },
        ),
    ]
