# Generated by Django 4.1.3 on 2024-04-10 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("coreapp", "0053_uploademployee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aptitudeone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topice", models.TextField()),
                ("upload", models.TextField()),
            ],
            options={
                "db_table": "Aptitudeone",
            },
        ),
        migrations.CreateModel(
            name="Cppfive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topice", models.TextField()),
                ("upload", models.TextField()),
            ],
            options={
                "db_table": "Cppfive",
            },
        ),
        migrations.CreateModel(
            name="Ctwo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topice", models.TextField()),
                ("upload", models.TextField()),
            ],
            options={
                "db_table": "Ctwo",
            },
        ),
        migrations.CreateModel(
            name="Englishsix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topice", models.TextField()),
                ("upload", models.TextField()),
            ],
            options={
                "db_table": "Englishsix",
            },
        ),
        migrations.CreateModel(
            name="Intershipseven",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topice", models.TextField()),
                ("upload", models.TextField()),
            ],
            options={
                "db_table": "Intershipseven",
            },
        ),
        migrations.CreateModel(
            name="Javathree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topice", models.TextField()),
                ("upload", models.TextField()),
            ],
            options={
                "db_table": "Javathree",
            },
        ),
        migrations.CreateModel(
            name="Jobten",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topice", models.TextField()),
                ("upload", models.TextField()),
            ],
            options={
                "db_table": "Jobten",
            },
        ),
        migrations.CreateModel(
            name="Pdnine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topice", models.TextField()),
                ("upload", models.TextField()),
            ],
            options={
                "db_table": "Pdnine",
            },
        ),
        migrations.CreateModel(
            name="Pythonfour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topice", models.TextField()),
                ("upload", models.TextField()),
            ],
            options={
                "db_table": "Pythonfour",
            },
        ),
        migrations.CreateModel(
            name="Workshopeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topice", models.TextField()),
                ("upload", models.TextField()),
            ],
            options={
                "db_table": "Workshopeight",
            },
        ),
        migrations.CreateModel(
            name="Userpermistionupload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "aptitude",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.aptitudeone",
                    ),
                ),
                (
                    "c",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.ctwo",
                    ),
                ),
                (
                    "cpp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.cppfive",
                    ),
                ),
                (
                    "english",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.englishsix",
                    ),
                ),
                (
                    "intership",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.intershipseven",
                    ),
                ),
                (
                    "java",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.javathree",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.jobten",
                    ),
                ),
                (
                    "pd",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.pdnine",
                    ),
                ),
                (
                    "python",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.pythonfour",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workshop",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coreapp.workshopeight",
                    ),
                ),
            ],
            options={
                "db_table": "Userpermistionupload",
            },
        ),
    ]
