# Generated by Django 4.1.3 on 2024-04-10 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("coreapp", "0054_aptitudeone_cppfive_ctwo_englishsix_intershipseven_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Userpermistionuploademployee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aptitude", models.BooleanField(default=False)),
                ("c", models.BooleanField(default=False)),
                ("java", models.BooleanField(default=False)),
                ("python", models.BooleanField(default=False)),
                ("cpp", models.BooleanField(default=False)),
                ("english", models.BooleanField(default=False)),
                ("intership", models.BooleanField(default=False)),
                ("workshop", models.BooleanField(default=False)),
                ("pd", models.BooleanField(default=False)),
                ("job", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "Userpermistionuploademployee",
            },
        ),
    ]
