# Generated by Django 4.1.3 on 2024-03-21 10:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("coreapp", "0045_cpptraingtitle_ctraingtitle_pythontraingtitle_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="demoskill",
            name="user",
        ),
        migrations.DeleteModel(
            name="Demoperson",
        ),
        migrations.DeleteModel(
            name="Demoskill",
        ),
    ]
